server:
  port: 8002

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Shtramak/spring-cloud-config-repo

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
